site_name: Kindershows
site_description: Deze repository bevat alle source code, scripts, en powerpoints voor de kindershows voor Intersoc.
site_author: Simon Meersschaut
site_url: https://SimonMeersschaut.github.io/kindershow/

theme:
  name: readthedocs
  palette:
    - scheme: default
      primary: blue
      accent: orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tasklist
  - attr_list
  - tables
  - admonition
  - toc
  - script_block

extra_css:
  - stylesheets/extra.css

# This section hooks up the MathJax scripts required to convert your LaTeX syntax into visual math on the page
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Start: index.md
  - Contributing: contributing.md
  - License: license.md
  - Shows:
    - Overzicht: shows/overzicht.md
    - Sketches:
      - Afleiding: shows/sketches/afleiding.md
      - Volgorde: shows/sketches/volgorde.md
      - Niesbui: shows/sketches/niesbui.md
      - Onzichtbare Muur: shows/sketches/onzichtbare-muur.md
      - Slechthorende Professor: shows/sketches/slechthorende-professor.md
      - Tijdvertrager: shows/sketches/tijdvertrager.md
      - Verkeerde ingredient: shows/sketches/verkeerde-ingredient.md
      - Verkeerde outfit: sketches/verkeerde-outfit.md
    - Dag 1: shows/dag1/script.md
    - Dag 2: shows/dag2/script.md
  - Erlemeyer:
    - Overzicht: erlemeyer/overzicht.md
    - 3d model: erlemeyer/3d-model.md
    - Electronics: erlemeyer/electronics.md
    - Code: erlemeyer/code.md

docs_dir: docs
site_dir: site