site_name: Kindershows
site_description: Deze repository bevat alle source code, scripts, en powerpoints voor de kindershows voor Intersoc.
site_author: Simon Meersschaut
site_url: https://SimonMeersschaut.github.io/kindershows/

theme:
  name: readthedocs
  palette:
    - scheme: default
      primary: blue
      accent: orange
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tasklist
  - attr_list
  - tables
  - admonition
  - toc

# This section hooks up the MathJax scripts required to convert your LaTeX syntax into visual math on the page
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Start: index.md
  - Shows:
    - Overzicht: shows/overzicht.md
    - Sketches:
      - afleiding: shows/sketches/afleiding.md
      - Groen of Rood: shows/sketches/groen-of-rood.md
      - Niesbui: shows/sketches/niesbui.md
      - Onzichtbare Muur: shows/sketches/onzichtbare-muur.md
      - Slechthorende Professor: shows/sketches/slechthorende-professor.md
      - Tijdvertrager: shows/sketches/tijdvertrager.md
      - Verkeerde ingredient: shows/sketches/verkeerde-ingredient.md
    - Dag 1: shows/dag1/script.md
  - Erlemeyer:
    - Overzicht: erlemeyer/overzicht.md
    - 3d model: erlemeyer/3d-model.md
    - electronics: erlemeyer/electronics.md
    - code: erlemeyer/code.md
  - Contributing: contributing.md
  - License: license.md

docs_dir: docs
site_dir: site